[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

#[programs.localnet]
[programs.devnet]
pivox_contract = "3zQWBv2YdLqZofanKcE4C7JEgM8PaL4Lemu6dZSqiNCv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=a992ac4f-6834-4e64-9f6f-1802d4d555c9"
wallet = "/home/vinay/Turbin3-wallet.json"
#wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
